language: python
python:
    - "2.7"
sudo: false

services:
  - docker

install: pip install -r requirements.txt

script:
    - docker build .
    - flake8 --ignore F401 securitybot/
    - PYTHONPATH=$(pwd) py.test -v tests/
